[package]
name = "hack4krak-macros"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "^2.0.116", features = ["full"] }
quote = "^1.0.44"

serde_norway.workspace = true